DATA:
  train_path: /datatmp/Datasets/intention_prediction/JAAD/processed_annotations/train.csv
  val_path: /datatmp/Datasets/intention_prediction/JAAD/processed_annotations/val.csv
  # val_path: null
  batch_size: 6
  num_workers: 6
  pin_memory: False
  desired_fps: 16
  input_seq_size: 4
  resize: 256
  overlap_percent: 0.8
  data_fps: 30
  image_mean: [0.45, 0.45, 0.45]
  image_std: [0.225, 0.225, 0.225]

TRAINING:
  gpus: 0
  epochs: 10
  lr: 0.00001
  betas: [0.9, 0.999]
  frac_train: 1.
  frac_val: 1.
  video_every: 20
  model_to_use: slow_r50
  log_every: 5

MODEL:
  model_num_class: 1
  model_pretraining: True

