DATA:
  train_path: /datatmp/Datasets/intention_prediction/PIE/processed_annotations/train.csv
  val_path: /datatmp/Datasets/intention_prediction/PIE/processed_annotations/val.csv
  # val_path: null
  dataset_type: detection
  weighted_sampler: True
  batch_size: 8
  num_workers: 8
  pin_memory: True
  desired_fps: 16
  input_seq_size: 4
  frame_future: 4
  resize: 256
  overlap_percent: 0.8
  data_fps: 30
  image_mean: [0.45, 0.45, 0.45]
  image_std: [0.225, 0.225, 0.225]
  scale_crop: 2

TRAINING:
  gpus: -1
  epochs: 5
  optimizer: adamw
  lr: 0.00001
  betas: [0.9, 0.999]
  frac_train: 1.
  frac_val: 1.
  video_every: 100
  model_to_use: slow
  log_every: 5
  save_checkpoints_every: 2000

MODEL:
  model_num_class: 1
  model_pretraining: x3d_xs

